import "./globals.css";
import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import { headers } from "next/headers";
import { type ReactNode } from "react";
import { cookieToInitialState } from "wagmi";

import { getConfig } from "../wagmi";
import { Providers } from "./providers";
import Header from "@/components/Header";
import ApolloProviderWrapper from "./apolloProvider";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sablier Clone",
  description: "Generated by create-wagmi",
  icons: {
    icon: "/images/favicon.ico",
  },
};

export default function RootLayout(props: { children: ReactNode }) {
  const initialState = cookieToInitialState(
    getConfig(),
    headers().get("cookie"),
  );
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={urbanist.className}>
        <Providers initialState={initialState}>
          <ApolloProviderWrapper>
            <section className="background-primary flex min-h-screen w-full flex-col">
              <Header />
              <div className="mx-auto size-full max-w-[1312px] flex-1 px-4">
                {props.children}
              </div>
            </section>
          </ApolloProviderWrapper>
        </Providers>
      </body>
    </html>
  );
}
