import './globals.css';
import type { Metadata } from 'next';
import { Urbanist } from 'next/font/google';
import { headers } from 'next/headers';
import { type ReactNode } from 'react';
import { cookieToInitialState } from 'wagmi';

import { getConfig } from '../wagmi';
import { Providers } from './providers';
import Header from '@/components/Header';

const urbanist = Urbanist({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Sablier Clone',
  description: 'Generated by create-wagmi',
  icons: {
    icon: '/images/favicon.ico',
  },
};

export default function RootLayout(props: { children: ReactNode }) {
  const initialState = cookieToInitialState(getConfig(), headers().get('cookie'));
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <Providers initialState={initialState}>
          <section className="w-full min-h-screen background-primary">
            <Header />
            <div className="w-full max-w-[1312px] mx-auto px-4">{props.children}</div>
          </section>
        </Providers>
      </body>
    </html>
  );
}
